name: Update AoC Badges
on:
  schedule:                  # run workflow based on schedule
    - cron: '6 5 1-12 12 *'  # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)
    
  workflow_dispatch:                             # allow to manually start the workflow 
  
# push:                                          # (disabled) run on push, be carefull with this setting 
                                                 # as the workflow should only be triggered at a rate lower than
                                                 # 4 times a hour to keep traffic on aoc site low 
                                                 
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2                # clones your repo
          
      - uses: joblo2213/aoc-badges-action@v3
        with:
          userid: 5257181                        # your user id, see setup on how to obtain
          session: ${{ secrets.AOC_SESSION }}    # secret containing session code, see setup on how to obtain
          
          # Optional inputs:
          # The year for which stats should be retrieved
          year: 2025
          # The url of the leaderboard from witch the data is fetched. Typically your private leaderboard.
          # leaderboard: 'https://adventofcode.com/2020/leaderboard/private/view/00000.json'               
          # The file that contains the badges
          file: 'README.md'                                                                              
          # Regular expression that finds the content of the day badge in your file.
          # dayRegex: '(?<=https:\/\/img\.shields\.io\/badge\/day%20ðŸ“…-)[0-9]+(?=-blue)'
          # Regular expression that finds the content of the stars badge in your file.
          starsRegex: '(?<=https:\/\/img\.shields\.io\/badge\/stars%202025â­-)[0-9]+(?=-yellow)' 
          # Regular expression that finds the content of the days completed badge iun your file.
          daysCompletedRegex: '(?<=https:\/\/img\.shields\.io\/badge\/days%20completed%202025âœ…-)[0-9]+(?=-red)'  

      # Step that pushes these local changes back to your github repo
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update badges
          file_pattern: README.md